version: '3'

services:
  frontend:
    image: eeacms/forests-frontend
    ports:
      - '${FRONTEND:-3000}:3000'
    environment:
      RAZZLE_INTERNAL_API_PATH: 'http://backend:8080/Plone'
      RAZZLE_DEV_PROXY_API_PATH: 'http://backend:8080/Plone'
    volumes:
      - ./src/addons:/app/src/addons
    depends_on:
      - backend

  backend:
    image: eeacms/plonesaas-devel
    ports:
      - '${BACKEND:-8080}:8080'
    environment:
      CORS_ALLOW_ORIGIN: 'http://localhost:3000,http://127.0.0.1:3000,http://localhost:${FRONTEND:-8000},http://127.0.0.1:${FRONTEND:-8000}'
    depends_on:
      - memcached
    volumes:
      - data:/data

  memcached:
    image: memcached
    command:
      - '-m'
      - '512'

volumes:
  data:
    driver: local
