/**
 * Add your action types here.
 * @module constants/ActionTypes
 * @example
 * export const UPDATE_CONTENT = 'UPDATE_CONTENT';
 */

export const GET_FRONTPAGESLIDES = 'GET_FRONTPAGESLIDES';
export const GET_DEFAULT_HEADER_IMAGE = 'GET_DEFAULT_HEADER_IMAGE';
export const SET_FOLDER_HEADER = 'SET_FOLDER_HEADER';
export const SET_FOLDER_TABS = 'SET_FOLDER_TABS';
export const GET_PARENT_FOLDER_DATA = 'GET_PARENT_FOLDER_DATA';
export const GET_MOSAIC_SETTINGS = 'GET_MOSAIC_SETTINGS';
// export const GET_DATA_PROVIDERS = 'GET_DATA_PROVIDERS';
export const GET_LOCALNAVIGATION = 'GET_LOCALNAVIGATION';
export const GET_CHART_DATA_FROM_VISUALIZATION =
  'GET_CHART_DATA_FROM_VISUALIZATION';
export const GET_NAVSITEMAP = 'GET_NAVSITEMAP';
// Facets
export const GET_KEYWORDS = 'GET_KEYWORDS';
export const GET_COUNTRY = 'GET_COUNTRY';
export const GET_DATA_SET = 'GET_DATA_SET';
export const GET_DATA_TYPE = 'GET_DATA_TYPE';
export const GET_INFO_LEVEL = 'GET_INFO_LEVEL';
export const GET_LANGUAGE = 'GET_LANGUAGE';
export const GET_NUTS_LEVEL = 'GET_NUTS_LEVEL';
export const GET_RESOURCE_TYPE = 'GET_RESOURCE_TYPE';
export const GET_TOPIC_CATEGORY = 'GET_TOPIC_CATEGORY';
export const GET_PUBLICATION_YEARS = 'GET_PUBLICATION_YEARS';