/**
 * Add your action types here.
 * @module constants/ActionTypes
 * @example
 * export const UPDATE_CONTENT = 'UPDATE_CONTENT';
 */

export const GET_FRONTPAGESLIDES = 'GET_FRONTPAGESLIDES';
export const GET_DEFAULT_HEADER_IMAGE = 'GET_DEFAULT_HEADER_IMAGE';
export const SET_FOLDER_HEADER = 'SET_FOLDER_HEADER';
export const SET_FOLDER_TABS = 'SET_FOLDER_TABS';
export const GET_PARENT_FOLDER_DATA = 'GET_PARENT_FOLDER_DATA';
export const GET_MOSAIC_SETTINGS = 'GET_MOSAIC_SETTINGS';
// export const GET_DATA_PROVIDERS = 'GET_DATA_PROVIDERS';
export const GET_DATA_FROM_PROVIDER = 'GET_DATA_FROM_PROVIDER';
export const GET_LOCALNAVIGATION = 'GET_LOCALNAVIGATION';
export const GET_CHART_DATA_FROM_VISUALIZATION =
  'GET_CHART_DATA_FROM_VISUALIZATION';

export const CREATE_ATTACHMENT = 'CREATE_ATTACHMENT';
export const GET_ALL_ATTACHMENTS = 'GET_ALL_ATTACHMENTS';
export const GET_ATTACHMENTS = 'GET_ATTACHMENTS';
export const UPDATE_ATTACHMENT = 'UPDATE_ATTACHMENT';
export const DELETE_ATTACHMENT = 'DELETE_ATTACHMENT';
